
mqtt.broker.url=${MQTT_PROTOCOL_URL}
mqtt.username=${MQTT_USER}
mqtt.password=${MQTT_PASSWORD}
mqtt.client.id=${MQTT_ID}
mqtt.topic=${MQTT_TOPIC}

spring.datasource.url=${DATA_BASE_URL}
spring.datasource.username=${DATA_BASE_USER}
spring.datasource.password=${DATA_BASE_PASSWORD}
spring.datasource.driver-class-name=${DATA_BASE_DRIVER}


spring.jpa.properties.hibernate.dialect=${DATA_BASE_DIALECT}
spring.jpa.hibernate.ddl-auto=${DDL_AUTO}


spring.jpa.show-sql=${SQL_JPA}

jwt.secret=${JWT_SECRET_KEY}
springdoc.api-docs.enabled=${SPRINGDOC_SWAGGER_UI_ENABLED}
springdoc.swagger-ui.enabled=${SPRINGDOC_API_DOCS_ENABLED}
